# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointment_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppointmentDialog(object):
    def setupUi(self, AppointmentDialog):
        AppointmentDialog.setObjectName("AppointmentDialog")
        AppointmentDialog.resize(500, 450)
        AppointmentDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        AppointmentDialog.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(AppointmentDialog)
        self.formLayout.setObjectName("formLayout")
        self.label_patient = QtWidgets.QLabel(AppointmentDialog)
        self.label_patient.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_patient.setObjectName("label_patient")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_patient)
        self.comboBox_patient = QtWidgets.QComboBox(AppointmentDialog)
        self.comboBox_patient.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_patient.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.comboBox_patient.setObjectName("comboBox_patient")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_patient)
        self.label_doctor = QtWidgets.QLabel(AppointmentDialog)
        self.label_doctor.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_doctor.setObjectName("label_doctor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_doctor)
        self.comboBox_doctor = QtWidgets.QComboBox(AppointmentDialog)
        self.comboBox_doctor.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_doctor.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.comboBox_doctor.setObjectName("comboBox_doctor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_doctor)
        self.label_appointmentDate = QtWidgets.QLabel(AppointmentDialog)
        self.label_appointmentDate.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_appointmentDate.setObjectName("label_appointmentDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_appointmentDate)
        self.dateEdit_appointmentDate = QtWidgets.QDateEdit(AppointmentDialog)
        self.dateEdit_appointmentDate.setMinimumSize(QtCore.QSize(0, 35))
        self.dateEdit_appointmentDate.setCalendarPopup(True)
        self.dateEdit_appointmentDate.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.dateEdit_appointmentDate.setObjectName("dateEdit_appointmentDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_appointmentDate)
        self.label_appointmentTime = QtWidgets.QLabel(AppointmentDialog)
        self.label_appointmentTime.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_appointmentTime.setObjectName("label_appointmentTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_appointmentTime)
        self.timeEdit_appointmentTime = QtWidgets.QTimeEdit(AppointmentDialog)
        self.timeEdit_appointmentTime.setMinimumSize(QtCore.QSize(0, 35))
        self.timeEdit_appointmentTime.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.timeEdit_appointmentTime.setObjectName("timeEdit_appointmentTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit_appointmentTime)
        self.label_status = QtWidgets.QLabel(AppointmentDialog)
        self.label_status.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_status)
        self.comboBox_status = QtWidgets.QComboBox(AppointmentDialog)
        self.comboBox_status.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_status.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.comboBox_status.setObjectName("comboBox_status")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.comboBox_status.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_status)
        self.label_notes = QtWidgets.QLabel(AppointmentDialog)
        self.label_notes.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_notes.setObjectName("label_notes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_notes)
        self.textEdit_notes = QtWidgets.QTextEdit(AppointmentDialog)
        self.textEdit_notes.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textEdit_notes.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.textEdit_notes.setObjectName("textEdit_notes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit_notes)
        self.buttonBox = QtWidgets.QDialogButtonBox(AppointmentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(AppointmentDialog)
        self.buttonBox.accepted.connect(AppointmentDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AppointmentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AppointmentDialog)

    def retranslateUi(self, AppointmentDialog):
        _translate = QtCore.QCoreApplication.translate
        AppointmentDialog.setWindowTitle(_translate("AppointmentDialog", "مدیریت نوبت"))
        self.label_patient.setText(_translate("AppointmentDialog", "بیمار:"))
        self.label_doctor.setText(_translate("AppointmentDialog", "پزشک:"))
        self.label_appointmentDate.setText(_translate("AppointmentDialog", "تاریخ نوبت:"))
        self.label_appointmentTime.setText(_translate("AppointmentDialog", "ساعت نوبت:"))
        self.label_status.setText(_translate("AppointmentDialog", "وضعیت:"))
        self.comboBox_status.setItemText(0, _translate("AppointmentDialog", "فعال"))
        self.comboBox_status.setItemText(1, _translate("AppointmentDialog", "انجام شده"))
        self.comboBox_status.setItemText(2, _translate("AppointmentDialog", "لغو شده"))
        self.comboBox_status.setItemText(3, _translate("AppointmentDialog", "به تعویق افتاده"))
        self.label_notes.setText(_translate("AppointmentDialog", "یادداشت:"))
        self.textEdit_notes.setPlaceholderText(_translate("AppointmentDialog", "یادداشت‌های مربوط به نوبت..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppointmentDialog = QtWidgets.QDialog()
    ui = Ui_AppointmentDialog()
    ui.setupUi(AppointmentDialog)
    AppointmentDialog.show()
    sys.exit(app.exec_())
