# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoctorDialog(object):
    def setupUi(self, DoctorDialog):
        DoctorDialog.setObjectName("DoctorDialog")
        DoctorDialog.resize(500, 500)
        DoctorDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        DoctorDialog.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(DoctorDialog)
        self.formLayout.setObjectName("formLayout")
        self.label_firstName = QtWidgets.QLabel(DoctorDialog)
        self.label_firstName.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_firstName.setObjectName("label_firstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_firstName)
        self.lineEdit_firstName = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_firstName.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_firstName)
        self.label_lastName = QtWidgets.QLabel(DoctorDialog)
        self.label_lastName.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_lastName.setObjectName("label_lastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_lastName)
        self.lineEdit_lastName = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_lastName.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lastName)
        self.label_specialty = QtWidgets.QLabel(DoctorDialog)
        self.label_specialty.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_specialty.setObjectName("label_specialty")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_specialty)
        self.lineEdit_specialty = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_specialty.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_specialty.setObjectName("lineEdit_specialty")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_specialty)
        self.label_phone = QtWidgets.QLabel(DoctorDialog)
        self.label_phone.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_phone.setObjectName("label_phone")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_phone)
        self.lineEdit_phone = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_phone.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_phone)
        self.label_email = QtWidgets.QLabel(DoctorDialog)
        self.label_email.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_email.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_email)
        self.label_licenseNumber = QtWidgets.QLabel(DoctorDialog)
        self.label_licenseNumber.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_licenseNumber.setObjectName("label_licenseNumber")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_licenseNumber)
        self.lineEdit_licenseNumber = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_licenseNumber.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_licenseNumber.setObjectName("lineEdit_licenseNumber")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_licenseNumber)
        self.label_officeNumber = QtWidgets.QLabel(DoctorDialog)
        self.label_officeNumber.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_officeNumber.setObjectName("label_officeNumber")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_officeNumber)
        self.lineEdit_officeNumber = QtWidgets.QLineEdit(DoctorDialog)
        self.lineEdit_officeNumber.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.lineEdit_officeNumber.setObjectName("lineEdit_officeNumber")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_officeNumber)
        self.label_consultationFee = QtWidgets.QLabel(DoctorDialog)
        self.label_consultationFee.setStyleSheet("font-weight: bold; color: #2c3e50;")
        self.label_consultationFee.setObjectName("label_consultationFee")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_consultationFee)
        self.doubleSpinBox_consultationFee = QtWidgets.QDoubleSpinBox(DoctorDialog)
        self.doubleSpinBox_consultationFee.setMaximum(10000000.0)
        self.doubleSpinBox_consultationFee.setStyleSheet("padding: 8px; border: 2px solid #ddd; border-radius: 4px; font-size: 12px;")
        self.doubleSpinBox_consultationFee.setObjectName("doubleSpinBox_consultationFee")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_consultationFee)
        self.buttonBox = QtWidgets.QDialogButtonBox(DoctorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(DoctorDialog)
        self.buttonBox.accepted.connect(DoctorDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DoctorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DoctorDialog)

    def retranslateUi(self, DoctorDialog):
        _translate = QtCore.QCoreApplication.translate
        DoctorDialog.setWindowTitle(_translate("DoctorDialog", "مدیریت پزشک"))
        self.label_firstName.setText(_translate("DoctorDialog", "نام:"))
        self.lineEdit_firstName.setPlaceholderText(_translate("DoctorDialog", "نام پزشک را وارد کنید"))
        self.label_lastName.setText(_translate("DoctorDialog", "نام خانوادگی:"))
        self.lineEdit_lastName.setPlaceholderText(_translate("DoctorDialog", "نام خانوادگی پزشک را وارد کنید"))
        self.label_specialty.setText(_translate("DoctorDialog", "تخصص:"))
        self.lineEdit_specialty.setPlaceholderText(_translate("DoctorDialog", "تخصص پزشک (مثل: قلب، مغز و اعصاب)"))
        self.label_phone.setText(_translate("DoctorDialog", "تلفن:"))
        self.lineEdit_phone.setPlaceholderText(_translate("DoctorDialog", "شماره تلفن"))
        self.label_email.setText(_translate("DoctorDialog", "ایمیل:"))
        self.lineEdit_email.setPlaceholderText(_translate("DoctorDialog", "آدرس ایمیل"))
        self.label_licenseNumber.setText(_translate("DoctorDialog", "شماره نظام پزشکی:"))
        self.lineEdit_licenseNumber.setPlaceholderText(_translate("DoctorDialog", "شماره نظام پزشکی"))
        self.label_officeNumber.setText(_translate("DoctorDialog", "شماره اتاق:"))
        self.lineEdit_officeNumber.setPlaceholderText(_translate("DoctorDialog", "شماره اتاق یا مطب"))
        self.label_consultationFee.setText(_translate("DoctorDialog", "هزینه ویزیت:"))
        self.doubleSpinBox_consultationFee.setSuffix(_translate("DoctorDialog", " تومان"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorDialog = QtWidgets.QDialog()
    ui = Ui_DoctorDialog()
    ui.setupUi(DoctorDialog)
    DoctorDialog.show()
    sys.exit(app.exec_())
