# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1200, 800)
        MainWindow.resize(1000, 500)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setStyleSheet("font-size: 24px; font-weight: bold; color: #2c3e50; margin: 20px;")
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.nav_layout = QtWidgets.QHBoxLayout()
        self.nav_layout.setObjectName("nav_layout")
        self.btn_patients = QtWidgets.QPushButton(self.centralwidget)
        self.btn_patients.setStyleSheet("QPushButton { background-color: #3498db; color: white; padding: 15px; font-size: 14px; border-radius: 5px; }")
        self.btn_patients.setObjectName("btn_patients")
        self.nav_layout.addWidget(self.btn_patients)
        self.btn_doctors = QtWidgets.QPushButton(self.centralwidget)
        self.btn_doctors.setStyleSheet("QPushButton { background-color: #2ecc71; color: white; padding: 15px; font-size: 14px; border-radius: 5px; }")
        self.btn_doctors.setObjectName("btn_doctors")
        self.nav_layout.addWidget(self.btn_doctors)
        self.btn_appointments = QtWidgets.QPushButton(self.centralwidget)
        self.btn_appointments.setStyleSheet("QPushButton { background-color: #e74c3c; color: white; padding: 15px; font-size: 14px; border-radius: 5px; }")
        self.btn_appointments.setObjectName("btn_appointments")
        self.nav_layout.addWidget(self.btn_appointments)
        self.verticalLayout.addLayout(self.nav_layout)
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setStyleSheet("QPushButton { background-color: #95a5a6; color: white; padding: 8px; }")
        self.btn_search.setObjectName("btn_search")
        self.search_layout.addWidget(self.btn_search)
        self.verticalLayout.addLayout(self.search_layout)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.operation_layout = QtWidgets.QHBoxLayout()
        self.operation_layout.setObjectName("operation_layout")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setStyleSheet("QPushButton { background-color: #27ae60; color: white; padding: 10px; font-size: 12px; border-radius: 3px; }")
        self.btn_add.setObjectName("btn_add")
        self.operation_layout.addWidget(self.btn_add)
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setStyleSheet("QPushButton { background-color: #f39c12; color: white; padding: 10px; font-size: 12px; border-radius: 3px; }")
        self.btn_edit.setObjectName("btn_edit")
        self.operation_layout.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setStyleSheet("QPushButton { background-color: #e74c3c; color: white; padding: 10px; font-size: 12px; border-radius: 3px; }")
        self.btn_delete.setObjectName("btn_delete")
        self.operation_layout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.operation_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "سیستم مدیریت بیمارستان"))
        self.label_title.setText(_translate("MainWindow", "سیستم مدیریت بیمارستان"))
        self.btn_patients.setText(_translate("MainWindow", "مدیریت بیماران"))
        self.btn_doctors.setText(_translate("MainWindow", "مدیریت پزشکان"))
        self.btn_appointments.setText(_translate("MainWindow", "مدیریت نوبت‌ها"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "جستجو..."))
        self.btn_search.setText(_translate("MainWindow", "جستجو"))
        self.btn_add.setText(_translate("MainWindow", "افزودن"))
        self.btn_edit.setText(_translate("MainWindow", "ویرایش"))
        self.btn_delete.setText(_translate("MainWindow", "حذف"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
